CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE SCHEMA IF NOT EXISTS reference;
CREATE SCHEMA IF NOT EXISTS iam;
CREATE SCHEMA IF NOT EXISTS organisation;
CREATE SCHEMA IF NOT EXISTS patient;
CREATE SCHEMA IF NOT EXISTS scheduling;
CREATE SCHEMA IF NOT EXISTS clinical;
CREATE SCHEMA IF NOT EXISTS nursing;
CREATE SCHEMA IF NOT EXISTS pharmacy;
CREATE SCHEMA IF NOT EXISTS diagnostics;
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS communication;
CREATE SCHEMA IF NOT EXISTS documents;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS integration;
CREATE SCHEMA IF NOT EXISTS reporting;

GRANT USAGE ON SCHEMA public, reference, iam, organisation, patient, scheduling, clinical, nursing,
    pharmacy, diagnostics, finance, communication, documents, audit, integration, reporting
    TO ${appRole};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA reference GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA iam GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA organisation GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA patient GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA scheduling GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA clinical GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA nursing GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA pharmacy GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA diagnostics GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA communication GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA documents GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA integration GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${appRole};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA reference GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA iam GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA organisation GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA patient GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA scheduling GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA clinical GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA nursing GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA pharmacy GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA diagnostics GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA communication GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA documents GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA integration GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${appRole};
